name: astro_etl_dbt
config-version: 2

vars:
  user_name: "Raphael"
  user_email: "rapha.wb@hotmail.com"

model-paths: ["models"]

models:
  astro_etl_dbt:
    materialized: view
    sales_stage:
      materialized: table
    sales_trusted:
      materialized: table
